version: "3"
services:
  sqlite:
    image: vivekraj59/sqlite
    build: .
    hostname: sqlite
    container_name: sqlite
    #environment:
    #  - name=value
    ports:
      - 8191:8191
    restart: unless-stopped
    volumes:
      - sqlitedb:/db
    networks:
      - sqlite

volumes:
  sqlitedb:
    name: sqlitedb
    external: false

networks:
  sqlite:
    name: sqlite
    driver: bridge
